### ISSUE TITLE
Support project switching

### ISSUE THREAD

**Issue by turtle0x1** [k3idii/python-lxd-gtk-indicator#1]
A drop-down perhaps at the top?

**Comment by k3idii** [comment]
what do you mean by that ?

**Comment by turtle0x1** [comment]
> what do you mean by that ?
In terms of design in html it would be a `<select></select>`

In terms of the API / concept explore the command/s `lxc project`. Projects is a way to divide up a `lxd` server. Its a broad topic so I wont go into detail here.

**Comment by k3idii** [comment]
Implemented in commit #43464b851cf8ef4accef62feea51640511ce75c0

**Comment by turtle0x1** [comment]
Excellent :smile: :+1: 

Not sure if you're aware but you can close an issue with a commit by adding `close #N` to the commit message, so in this case it would be `support for project switching close #1` (you can also put it in a pull request body)

**Comment by k3idii** [comment]
Still learning new stuff ;) tx.
Hope you find this tool usefull.
